# Generated by Django 5.2 on 2025-09-01 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_new_posts', models.BooleanField(default=True, help_text='Nuevos posts en comunidades suscritas')),
                ('app_new_comments', models.BooleanField(default=True, help_text='Comentarios en tus posts')),
                ('app_comment_replies', models.BooleanField(default=True, help_text='Respuestas a tus comentarios')),
                ('app_new_ratings', models.BooleanField(default=True, help_text='Nuevas valoraciones de reputación')),
                ('email_new_ratings', models.BooleanField(default=True, help_text='Valoraciones importantes por email')),
                ('email_important_comments', models.BooleanField(default=True, help_text='Comentarios importantes por email')),
                ('email_weekly_summary', models.BooleanField(default=True, help_text='Resumen semanal de actividad')),
                ('summary_frequency', models.CharField(choices=[('immediate', 'Inmediato'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('never', 'Nunca')], default='weekly', help_text='Frecuencia de emails de resumen', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Inicio de horas silenciosas (opcional)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin de horas silenciosas (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_POST', 'Nuevo post en comunidad'), ('NEW_COMMENT', 'Comentario en tu post'), ('COMMENT_REPLY', 'Respuesta a tu comentario'), ('NEW_RATING', 'Nueva valoración recibida'), ('COMMUNITY_JOIN', 'Nuevo miembro en comunidad administrada'), ('COMMUNITY_MENTION', 'Mención en comunidad')], db_index=True, help_text='Tipo de notificación', max_length=20)),
                ('title', models.CharField(help_text='Título corto de la notificación', max_length=255)),
                ('message', models.TextField(help_text='Mensaje descriptivo de la notificación')),
                ('object_id', models.PositiveIntegerField(help_text='ID del objeto relacionado')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='¿Ha sido leída por el usuario?')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', help_text='Prioridad de la notificación', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación')),
                ('read_at', models.DateTimeField(blank=True, help_text='Fecha en que fue leída', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='¿Se envió email de respaldo?')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Fecha de envío del email', null=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de contenido relacionado', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'type', '-created_at'], name='notificatio_user_id_3b3832_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['email_sent', 'created_at'], name='notificatio_email_s_46fded_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'NORMAL', 'HIGH', 'URGENT'])), name='valid_priority')],
            },
        ),
    ]
