# Generated by Django 5.2 on 2025-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_comments',
            field=models.BooleanField(default=True, help_text='Emails por nuevos comentarios'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_critical',
            field=models.BooleanField(default=True, help_text='Emails por alertas críticas (seguridad, moderación)'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar notificaciones por email'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_frequency',
            field=models.CharField(choices=[('immediate', 'Inmediato'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('never', 'Nunca')], default='immediate', help_text='Frecuencia de emails normales', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_invites',
            field=models.BooleanField(default=True, help_text='Emails por invitaciones a comunidades'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_posts',
            field=models.BooleanField(default=True, help_text='Emails por nuevos posts'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_reactions',
            field=models.BooleanField(default=False, help_text='Emails por reacciones a posts'),
        ),
    ]
