# Generated by Django 5.2 on 2025-09-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreferences_email_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='¿Se envió notificación por email?'),
        ),
    ]
