# Generated by Django 5.2 on 2025-08-14 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Biografía del usuario (máximo 500 caracteres)', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Ubicación del usuario', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('favorite_games', models.JSONField(blank=True, default=list, help_text='Lista de juegos favoritos')),
                ('play_style', models.CharField(blank=True, choices=[('competitive', 'Competitivo'), ('casual', 'Casual'), ('collector', 'Coleccionista'), ('trader', 'Intercambiador'), ('content_creator', 'Creador de Contenido')], help_text='Estilo de juego preferido', max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], help_text='Nivel de experiencia en TCGs', max_length=20)),
                ('avatar_url', models.URLField(blank=True, help_text='URL del avatar del usuario', null=True)),
                ('banner_url', models.URLField(blank=True, help_text='URL del banner del perfil', null=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='system', help_text='Preferencia de tema visual', max_length=20)),
                ('show_email', models.BooleanField(default=False, help_text='Mostrar email públicamente')),
                ('show_location', models.BooleanField(default=True, help_text='Mostrar ubicación públicamente')),
                ('show_birth_date', models.BooleanField(default=False, help_text='Mostrar fecha de nacimiento públicamente')),
                ('show_communities', models.BooleanField(default=True, help_text='Mostrar comunidades públicamente')),
                ('show_activity_stats', models.BooleanField(default=True, help_text='Mostrar estadísticas de actividad públicamente')),
                ('communities_count', models.IntegerField(default=0, help_text='Número de comunidades en las que participa')),
                ('posts_count', models.IntegerField(default=0, help_text='Número total de publicaciones')),
                ('likes_received', models.IntegerField(default=0, help_text='Número total de likes recibidos')),
                ('reputation_score', models.IntegerField(default=0, help_text='Puntuación de reputación (para Fase 4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
