# Generated by Django 5.2 on 2025-08-26 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ - Muy Malo'), (2, '⭐⭐ - Malo'), (3, '⭐⭐⭐ - Regular'), (4, '⭐⭐⭐⭐ - Bueno'), (5, '⭐⭐⭐⭐⭐ - Excelente')], help_text='Valoración de 1 a 5 estrellas')),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional sobre la valoración (máximo 300 caracteres)', max_length=300)),
                ('interaction_type', models.CharField(choices=[('trade', 'Intercambio de cartas'), ('game', 'Partida/Duelo'), ('tournament', 'Torneo'), ('community', 'Actividad en comunidad'), ('help', 'Ayuda/Asesoría'), ('general', 'Interacción general')], default='general', help_text='Tipo de interacción que motivó la valoración', max_length=30)),
                ('interaction_reference', models.CharField(blank=True, help_text='Referencia opcional a la interacción específica (ID de post, torneo, etc.)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Si la valoración está activa (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated_user', models.ForeignKey(help_text='Usuario que recibe la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(help_text='Usuario que otorga la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rated_user', 'is_active'], name='users_userr_rated_u_8c775c_idx'), models.Index(fields=['rater', 'is_active'], name='users_userr_rater_i_33f79e_idx'), models.Index(fields=['rating', 'is_active'], name='users_userr_rating_5e5ab0_idx'), models.Index(fields=['interaction_type'], name='users_userr_interac_325c08_idx')],
                'unique_together': {('rater', 'rated_user')},
            },
        ),
    ]
