# Generated by Django 5.2 on 2025-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_count',
            field=models.IntegerField(default=0, help_text='Número total de valoraciones recibidas activas'),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Puntuación de reputación calculada (0.00-5.00)', max_digits=4),
        ),
    ]
