# Generated by Django 5.2 on 2025-08-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_reputation_count_user_reputation_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('mutual_rating_circle', 'Círculo de Valoración Mutua'), ('five_star_bias', 'Sesgo de 5 Estrellas'), ('rating_burst', 'Ráfaga de Valoraciones'), ('inactive_user_ratings', 'Valoraciones a Usuarios Inactivos'), ('same_ip_ratings', 'Valoraciones desde Misma IP'), ('new_account_spam', 'Spam de Cuenta Nueva'), ('suspicious_pattern', 'Patrón Sospechoso General')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Detalles específicos del flag detectado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('resolved', 'Resuelto'), ('false_positive', 'Falso Positivo')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='users.userrating')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension_type', models.CharField(choices=[('warning', 'Advertencia'), ('temporary', 'Suspensión Temporal'), ('permanent', 'Suspensión Permanente'), ('rating_ban', 'Prohibición de Valorar')], max_length=20)),
                ('reason', models.CharField(choices=[('gaming_detection', 'Gaming del Sistema Detectado'), ('abuse_pattern', 'Patrón de Abuso'), ('false_ratings', 'Valoraciones Falsas'), ('harassment', 'Acoso a Otros Usuarios'), ('multiple_accounts', 'Múltiples Cuentas'), ('manual_review', 'Revisión Manual'), ('community_violation', 'Violación de Normas')], max_length=50)),
                ('reason_details', models.TextField(help_text='Descripción detallada del motivo de suspensión')),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración (null = permanente)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_suspensions', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_suspensions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='AbuseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('flag_created', 'Flag Creado'), ('flag_reviewed', 'Flag Revisado'), ('flag_resolved', 'Flag Resuelto'), ('user_suspended', 'Usuario Suspendido'), ('suspension_lifted', 'Suspensión Levantada'), ('rating_blocked', 'Valoración Bloqueada'), ('pattern_detected', 'Patrón Detectado'), ('manual_review', 'Revisión Manual'), ('config_changed', 'Configuración Cambiada'), ('system_alert', 'Alerta del Sistema')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Detalles específicos de la acción ejecutada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_logs_as_moderator', to=settings.AUTH_USER_MODEL)),
                ('related_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userrating')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_logs_as_target', to=settings.AUTH_USER_MODEL)),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ratingflag')),
                ('related_suspension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersuspension')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AntiAbuseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clave única de configuración (ej: daily_rating_limit)', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('rate_limiting', 'Rate Limiting'), ('detection_thresholds', 'Umbrales de Detección'), ('suspension_rules', 'Reglas de Suspensión'), ('notification_settings', 'Configuración de Notificaciones'), ('general_settings', 'Configuración General')], default='general_settings', max_length=50)),
                ('value', models.JSONField(help_text='Valor de configuración (puede ser número, string, dict, etc.)')),
                ('description', models.TextField(help_text='Descripción de qué controla esta configuración')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Reglas de validación para el valor (ej: min, max, type)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='users_antia_categor_db02f9_idx'), models.Index(fields=['key', 'is_active'], name='users_antia_key_7ab730_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['flag_type', 'severity'], name='users_ratin_flag_ty_2f5d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['status', 'created_at'], name='users_ratin_status_dd11e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['rating', 'flag_type'], name='users_ratin_rating__9fea08_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_7270c3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['suspension_type', 'is_active'], name='users_users_suspens_bec13d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersuspension',
            index=models.Index(fields=['expires_at', 'is_active'], name='users_users_expires_12b81a_idx'),
        ),
        migrations.AddIndex(
            model_name='abuselog',
            index=models.Index(fields=['action_type', 'timestamp'], name='users_abuse_action__f31482_idx'),
        ),
        migrations.AddIndex(
            model_name='abuselog',
            index=models.Index(fields=['target_user', 'timestamp'], name='users_abuse_target__0b9070_idx'),
        ),
        migrations.AddIndex(
            model_name='abuselog',
            index=models.Index(fields=['moderator', 'timestamp'], name='users_abuse_moderat_0c93fc_idx'),
        ),
    ]
