# Generated by Django 5.2 on 2025-08-14 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría (ej: Competitive, Casual)', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version del nombre (se genera automáticamente)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de qué tipo de comunidades incluye esta categoría')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono Material Design (ej: emoji_events, group)', max_length=50)),
                ('color', models.CharField(default='#2196F3', help_text='Color en formato hex (ej: #FF5722)', max_length=7)),
                ('community_count', models.IntegerField(default=0, help_text='Número de comunidades en esta categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Si la categoría está disponible para nuevas comunidades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Comunidad',
                'verbose_name_plural': 'Categorías de Comunidades',
                'ordering': ['-community_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la comunidad (3-100 caracteres)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(help_text='Descripción detallada de la comunidad y sus objetivos')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', unique=True)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen de portada de la comunidad', null=True, validators=[django.core.validators.URLValidator()])),
                ('game_type', models.CharField(help_text='Tipo de juego TCG (ej: Magic: The Gathering, Pokemon, Yu-Gi-Oh)', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', help_text='Nivel de experiencia requerido', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Si la comunidad es visible públicamente')),
                ('requires_approval', models.BooleanField(default=False, help_text='Si las solicitudes de membresía requieren aprobación manual')),
                ('max_members', models.IntegerField(blank=True, help_text='Límite máximo de miembros (null = sin límite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la comunidad')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('member_count', models.IntegerField(default=0, help_text='Número actual de miembros activos')),
                ('post_count', models.IntegerField(default=0, help_text='Número total de posts en la comunidad')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de tags para búsqueda y filtrado')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la comunidad', on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Categoría temática de la comunidad', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.communitycategory')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['-member_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('moderator', 'Moderador'), ('admin', 'Administrador')], default='member', help_text='Rol del usuario en la comunidad', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente de Aprobación'), ('suspended', 'Suspendido'), ('banned', 'Expulsado')], default='active', help_text='Estado actual de la membresía', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se unió a la comunidad')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del estado/rol')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre la membresía (visible solo para moderadores)')),
                ('community', models.ForeignKey(help_text='Comunidad a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('invited_by', models.ForeignKey(blank=True, help_text='Usuario que invitó a este miembro (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario miembro de la comunidad', on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de Comunidad',
                'verbose_name_plural': 'Membresías de Comunidades',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['game_type'], name='communities_game_ty_6f6154_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['difficulty_level'], name='communities_difficu_620f41_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['is_public'], name='communities_is_publ_6bcd00_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-member_count'], name='communities_member__b80a75_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created_at'], name='communities_created_54da6c_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_1e5b66_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'role'], name='communities_communi_5808bc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['status'], name='communities_status_89dd29_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['-joined_at'], name='communities_joined__627138_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
    ]
