# Generated by Django 5.2 on 2025-08-14 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre oficial del juego TCG', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del juego y sus características principales')),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo oficial del juego', null=True)),
                ('publisher', models.CharField(blank=True, help_text='Editorial o compañía que publica el juego', max_length=100)),
                ('release_year', models.IntegerField(blank=True, help_text='Año de lanzamiento del juego', null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('min_players', models.IntegerField(default=2, help_text='Número mínimo de jugadores', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_players', models.IntegerField(blank=True, help_text='Número máximo de jugadores (null = sin límite)', null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('is_active', models.BooleanField(default=True, help_text='Si el juego está activo para nuevas comunidades')),
                ('is_featured', models.BooleanField(default=False, help_text='Si el juego aparece en la sección destacada')),
                ('community_count', models.IntegerField(default=0, help_text='Número de comunidades asociadas (actualizado automáticamente)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Game Type',
                'verbose_name_plural': 'Game Types',
                'ordering': ['-is_featured', '-community_count', 'name'],
                'indexes': [models.Index(fields=['is_featured', '-community_count'], name='communities_is_feat_e5e1bb_idx'), models.Index(fields=['is_active'], name='communities_is_acti_732f83_idx'), models.Index(fields=['slug'], name='communities_slug_122b95_idx')],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='game_type_new',
            field=models.ForeignKey(blank=True, help_text='Nueva referencia a GameType (temporal para migración)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.gametype'),
        ),
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tag (2-30 caracteres, solo alfanuméricos)', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Tag solo puede contener letras, números, guiones y guiones bajos', regex='^[a-zA-Z0-9-_]+$')])),
                ('display_name', models.CharField(blank=True, help_text='Nombre para mostrar (con espacios y mayúsculas)', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Descripción breve del significado del tag', max_length=100)),
                ('usage_count', models.IntegerField(default=0, help_text='Número de comunidades que usan este tag')),
                ('is_suggested', models.BooleanField(default=False, help_text='Si aparece en sugerencias automáticas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del tag')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Tag',
                'verbose_name_plural': 'Community Tags',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['-usage_count'], name='communities_usage_c_04ff10_idx'), models.Index(fields=['is_suggested'], name='communities_is_sugg_519543_idx'), models.Index(fields=['name'], name='communities_name_deb212_idx')],
            },
        ),
    ]
