# Generated by Django 5.2 on 2025-08-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_migrate_game_type_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='community',
            new_name='communities_game_ty_6789cc_idx',
            old_name='communities_game_ty_6f6154_idx',
        ),
        migrations.RemoveField(
            model_name='community',
            name='game_type_new',
        ),
        migrations.AlterField(
            model_name='community',
            name='game_type',
            field=models.ForeignKey(help_text='Tipo de juego TCG asociado a esta comunidad', on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.gametype'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tags para clasificación adicional (máximo 10)'),
        ),
    ]
