# Generated by Django 5.2 on 2025-08-18 03:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_rename_communities_game_ty_6f6154_idx_communities_game_ty_6789cc_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional del post (máximo 200 caracteres)', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('content', models.TextField(help_text='Contenido principal del post (1-10,000 caracteres)', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10000)])),
                ('image_urls_json', models.TextField(blank=True, default='[]', help_text='URLs de imágenes en formato JSON (máximo 5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si False, el post está eliminado (soft delete)')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Número total de comentarios (actualizado automáticamente)')),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Número total de reacciones (actualizado automáticamente)')),
                ('author', models.ForeignKey(help_text='Usuario autor del post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(help_text='Comunidad donde se publica el post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_level', models.PositiveIntegerField(default=0, help_text='Nivel de profundidad en el thread (0=comentario principal)')),
                ('thread_path', models.CharField(blank=True, help_text='Ruta completa del thread para ordenamiento eficiente', max_length=500)),
                ('content', models.TextField(help_text='Contenido del comentario (1-2,000 caracteres)', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si False, el comentario está eliminado (soft delete)')),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Número total de reacciones (actualizado automáticamente)')),
                ('replies_count', models.PositiveIntegerField(default=0, help_text='Número de respuestas directas (actualizado automáticamente)')),
                ('author', models.ForeignKey(help_text='Usuario autor del comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Comentario padre para threading (respuestas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communities.comment')),
                ('post', models.ForeignKey(help_text='Post al que pertenece este comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['thread_path', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID del objeto (post o comment)')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Me gusta'), ('love', '❤️ Me encanta'), ('laugh', '😂 Me divierte'), ('wow', '😮 Me sorprende'), ('sad', '😢 Me entristece'), ('angry', '😠 Me molesta')], help_text='Tipo de reacción emoji', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de contenido (post o comment)', limit_choices_to={'model__in': ('post', 'comment')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Usuario que hizo la reacción', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='posts_community_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', '-created_at'], name='posts_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', 'is_active', '-created_at'], name='posts_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('content__isnull', False)), name='post_content_not_null'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'thread_path', 'created_at'], name='comments_post_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='comments_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_parent_date_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_active', '-created_at'], name='comments_active_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('content__isnull', False)), name='comment_content_not_null'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('thread_level__lte', 2)), name='comment_max_thread_level'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content_type', 'object_id', 'reaction_type'], name='reactions_content_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', '-created_at'], name='reactions_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='reactions_content_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(('reaction_type__in', ['like', 'love', 'laugh', 'wow', 'sad', 'angry'])), name='reaction_valid_type'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
