# Generated by Django 5.2.4 on 2025-08-18 22:54

import communities.models.post_image
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_post_comment_reaction_post_posts_community_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Imagen original subida por el usuario', upload_to=communities.models.post_image.post_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('large_path', models.CharField(blank=True, help_text='Path de la imagen en resolución large (1200x900)', max_length=500)),
                ('medium_path', models.CharField(blank=True, help_text='Path de la imagen en resolución medium (800x600)', max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path de la imagen en resolución thumbnail (150x150)', max_length=500)),
                ('original_filename', models.CharField(help_text='Nombre original del archivo subido', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño del archivo original en bytes')),
                ('width', models.PositiveIntegerField(help_text='Ancho de la imagen original en píxeles')),
                ('height', models.PositiveIntegerField(help_text='Alto de la imagen original en píxeles')),
                ('content_type', models.CharField(help_text='MIME type del archivo (ej: image/jpeg)', max_length=100)),
                ('processed', models.BooleanField(default=False, help_text='Indica si se generaron todas las resoluciones')),
                ('is_active', models.BooleanField(default=True, help_text='Permite soft delete de imágenes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden de la imagen en el post (0=primera)')),
                ('post', models.ForeignKey(help_text='Post al que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='communities.post')),
            ],
            options={
                'verbose_name': 'Imagen de Post',
                'verbose_name_plural': 'Imágenes de Posts',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'is_active', 'order'], name='postimg_post_active_order_idx'), models.Index(fields=['processed'], name='postimg_processed_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('post', 'order'), name='unique_active_image_order_per_post')],
            },
        ),
    ]
